version: '3.5'

services:

  groundschool-ui:
    container_name: groundschool-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:4200'
