application:
  host: ${application.host}
  security:
    secret: ${application.security.secret}
    expiration-time: ${application.security.expiration-time}

spring:
  datasource:
    url: ${spring_datasource_url}
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gcp:
      sql:
        database-name: ${spring_cloud_gcp_sql_database_name}
        instance-connection-name: ${spring_cloud_gcp_sql_instance_connection_name}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

logging:
  level:
    org:
     hibernate:
       SQL: INFO
       #type: TRACE

hazelcast:
  cache:
    # time to live in seconds
    ttl: ${hazelcast.cache.ttl}

groundschool:
  timeout:
    read: ${groundschool.timeout.read}
    connect: ${groundschool.timeout.connect}
    access-token-validity: ${groundschool.timeout.access-token-validity}
  email:
    from-address: ${groundschool.email.from-address}
    host: ${groundschool.email.host}
    port: ${groundschool.email.port}
    username: ${groundschool.email.username}
    password: ${groundschool.email.password}
  sms:
    from-address: ${groundschool.sms.from-address}
    account-sid: ${groundschool.sms.account-sid}
    auth-id: ${groundschool.sms.auth-id}

slack:
  bot:
    key: ${slack.bot.key}
    channel: ${slack.bot.channel}
    name: ${slack.bot.name}
