server:
  contextPath: /user-portal

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eaa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

logging:
  level:
    org:
     hibernate:
       SQL: DEBUG
       type: TRACE

EAA690:
  authentication:
    username: brian.michael@yahoo.com
    password: jaoudy
    signing-key: <<HIDDEN>>
    token-prefix: "Bearer "
    authorities-key: scopes
    header-string: Authorization

groundschool:
  timeout:
    read: 10000
    connect: 1000
    access-token-validity: 18000000