server:
  contextPath: /user-portal

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bsmichael@gmail.com
    password: <<HIDDEN>>
    #protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  datasource:
    url: jdbc:mysql://localhost:3306/eaa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

logging:
  level:
    org:
     hibernate:
       SQL: INFO
       #type: TRACE

EAA690:
  authentication:
    username: brian.michael@yahoo.com
    password: jaoudy
    signing-key: <<HIDDEN>>
    token-prefix: "Bearer "
    authorities-key: scopes
    header-string: Authorization

groundschool:
  timeout:
    read: 10000
    connect: 1000
    access-token-validity: 18000000
  email:
    from-address: bsmichael@gmail.com
    bcc-address: bsmichael@gmail.com
  sms:
    from-address: 4047355660
  slack:
    from-address: brianmichael