server:
  contextPath: /user-portal

spring:
  datasource:
    url: jdbc:mysql://35.185.77.211:3306/groundschool
    username: root
    password: <<HIDDEN>>
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

logging:
  level:
    org:
     hibernate:
       SQL: INFO
       #type: TRACE

EAA690:
  authentication:
    username: brian.michael@yahoo.com
    password: <<HIDDEN>>
    signing-key: <<HIDDEN>>
    token-prefix: "Bearer "
    authorities-key: scopes
    header-string: Authorization

groundschool:
  admin:
    # for testing, password is "password"
    password: "$2a$04$nUo76pGPgQna4oj.1CsfVuSJk9CUZZjpsbe6E/Ai39dPr4RQiiKHi"
  timeout:
    read: 10000
    connect: 1000
    access-token-validity: 18000000
  email:
    from-address: bsmichael@gmail.com
    bcc-address: bsmichael@gmail.com
    host: smtp.gmail.com
    port: 587
    username: bsmichael@gmail.com
    password: <<HIDDEN>>
  sms:
    from-address: +15005550006
    account-sid: <<HIDDEN>>
    auth-id: <<HIDDEN>>
  slack:
    from-address: groundschool

# slack integrations
# Note: these must be top level settings
slackApi: https://slack.com/api
slackBotToken: <<HIDDEN>>
slashCommandToken: <<HIDDEN>>
# replace the below url with your slack webhook url
slackIncomingWebhookUrl: <<HIDDEN>>

# fb bot
fbGraphApi: https://graph.facebook.com/v3.2
fbBotToken: fb_token_for_jbot
fbPageAccessToken: <paste your page access token>