server:
  contextPath: /user-portal

application:
  host: http://localhost:8080
  security:
    secret: ElFlacoBrion
    expiration-time: 86000

spring:
  datasource:
    url: jdbc:mysql://35.185.77.211:3306/groundschool
    username: root
    password: Sw33tDr34ms
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

logging:
  level:
    org:
     hibernate:
       SQL: INFO
       #type: TRACE

hazelcast:
  cache:
    # time to live in seconds
    ttl: 300

EAA690:
  authentication:
    username: brian.michael@yahoo.com
    password: swonk1on
    signing-key: <<HIDDEN>>
    token-prefix: "Bearer "
    authorities-key: scopes
    header-string: Authorization

groundschool:
  timeout:
    read: 10000
    connect: 1000
    access-token-validity: 18000000
  email:
    from-address: bsmichael@gmail.com
    bcc-address: bsmichael@gmail.com
    host: smtp.gmail.com
    port: 587
    username: bsmichael@gmail.com
    password: swonk1on
  sms:
    from-address: +15005550006
    account-sid: ACe05df43fe06b985d63995b4decf1e5d8
    auth-id: c6da2d9ddab64899992cf8a0adcf27ce
  slack:
    from-address: brianmichael

slack:
  bot:
    key: xoxb-377129945713-532745405744-UBdLFUyXYJtUQhsdrCz3Dm0M
    channel: groundschool
    name: groundschool
