/*
 *-----------------------------------------------------------------------------
 * Copyright 2018 Starfire Aviation, LLC
 *-----------------------------------------------------------------------------
 */
package com.starfireaviation.groundschool.model;

/**
 * StatisticType
 *
 * @author brianmichael
 */
public enum StatisticType {

    /**
     * USER_SAVED
     */
    USER_SAVED,
    /**
     * USER_DELETED
     */
    USER_DELETED,
    /**
     * REFERENCE_MATERIAL_SAVED
     */
    REFERENCE_MATERIAL_SAVED,
    /**
     * REFERENCE_MATERIAL_DELETED
     */
    REFERENCE_MATERIAL_DELETED,
    /**
     * QUIZ_SAVED
     */
    QUIZ_SAVED,
    /**
     * QUIZ_DELETED
     */
    QUIZ_DELETED,
    /**
     * QUESTION_SAVED
     */
    QUESTION_SAVED,
    /**
     * QUESTION_DELETED
     */
    QUESTION_DELETED,
    /**
     * MEMBER_DETAILS_SAVED
     */
    MEMBER_DETAILS_SAVED,
    /**
     * MEMBER_DETAILS_DELETED
     */
    MEMBER_DETAILS_DELETED,
    /**
     * REBUILD_MEMBER_DETAILS
     */
    REBUILD_MEMBER_DETAILS,
    /**
     * EVENT_CREATED
     */
    EVENT_CREATED,
    /**
     * EVENT_UPDATED
     */
    EVENT_UPDATED,
    /**
     * EVENT_CANCELLED
     */
    EVENT_CANCELLED,
    /**
     * SLACK_EVENT_CREATED_NOTIFICATION
     */
    SLACK_EVENT_CREATED_NOTIFICATION,
    /**
     * SLACK_EVENT_CANCELLED_NOTIFICATION
     */
    SLACK_EVENT_CANCELLED_NOTIFICATION,
    /**
     * SLACK_EVENT_UPDATED_NOTIFICATION
     */
    SLACK_EVENT_UPDATED_NOTIFICATION,
    /**
     * SLACK_EVENT_STARTED_NOTIFICATION
     */
    SLACK_EVENT_STARTED_NOTIFICATION,
    /**
     * FACEBOOK_EVENT_CREATED_NOTIFICATION
     */
    FACEBOOK_EVENT_CREATED_NOTIFICATION,
    /**
     * FACEBOOK_EVENT_CANCELLED_NOTIFICATION
     */
    FACEBOOK_EVENT_CANCELLED_NOTIFICATION,
    /**
     * FACEBOOK_EVENT_UPDATED_NOTIFICATION
     */
    FACEBOOK_EVENT_UPDATED_NOTIFICATION,
    /**
     * FACEBOOK_EVENT_STARTED_NOTIFICATION
     */
    FACEBOOK_EVENT_STARTED_NOTIFICATION,
    /**
     * SLACK_MESSAGE_SENT
     */
    SLACK_MESSAGE_SENT,
    /**
     * INSTAGRAM_EVENT_CREATED_NOTIFICATION
     */
    INSTAGRAM_EVENT_CREATED_NOTIFICATION,
    /**
     * INSTAGRAM_EVENT_CANCELLED_NOTIFICATION
     */
    INSTAGRAM_EVENT_CANCELLED_NOTIFICATION,
    /**
     * INSTAGRAM_EVENT_UPDATED_NOTIFICATION
     */
    INSTAGRAM_EVENT_UPDATED_NOTIFICATION,
    /**
     * INSTAGRAM_EVENT_STARTED_NOTIFICATION
     */
    INSTAGRAM_EVENT_STARTED_NOTIFICATION,
    /**
     * TWITTER_EVENT_CREATED_NOTIFICATION
     */
    TWITTER_EVENT_CREATED_NOTIFICATION,
    /**
     * TWITTER_EVENT_CANCELLED_NOTIFICATION
     */
    TWITTER_EVENT_CANCELLED_NOTIFICATION,
    /**
     * TWITTER_EVENT_UPDATED_NOTIFICATION
     */
    TWITTER_EVENT_UPDATED_NOTIFICATION,
    /**
     * TWITTER_EVENT_STARTED_NOTIFICATION
     */
    TWITTER_EVENT_STARTED_NOTIFICATION,
    /**
     * GCALENDAR_EVENT_CREATED_NOTIFICATION
     */
    GCALENDAR_EVENT_CREATED_NOTIFICATION,
    /**
     * GCALENDAR_EVENT_CANCELLED_NOTIFICATION
     */
    GCALENDAR_EVENT_CANCELLED_NOTIFICATION,
    /**
     * GCALENDAR_EVENT_UPDATED_NOTIFICATION
     */
    GCALENDAR_EVENT_UPDATED_NOTIFICATION,
    /**
     * GCALENDAR_EVENT_STARTED_NOTIFICATION
     */
    GCALENDAR_EVENT_STARTED_NOTIFICATION,
    /**
     * EMAIL_EVENT_CREATED_NOTIFICATION
     */
    EMAIL_EVENT_CREATED_NOTIFICATION,
    /**
     * EMAIL_EVENT_CANCELLED_NOTIFICATION
     */
    EMAIL_EVENT_CANCELLED_NOTIFICATION,
    /**
     * EMAIL_EVENT_UPDATED_NOTIFICATION
     */
    EMAIL_EVENT_UPDATED_NOTIFICATION,
    /**
     * EMAIL_EVENT_RSVP_NOTIFICATION
     */
    EMAIL_EVENT_RSVP_NOTIFICATION,
    /**
     * EMAIL_EVENT_STARTED_NOTIFICATION
     */
    EMAIL_EVENT_STARTED_NOTIFICATION,
    /**
     * EMAIL_INVITATION_SENT
     */
    EMAIL_INVITATION_SENT,
    /**
     * ANSWER_CREATED
     */
    ANSWER_CREATED,
    /**
     * ANSWER_UPDATED
     */
    ANSWER_UPDATED,
    /**
     * ANSWER_DELETED
     */
    ANSWER_DELETED,
    /**
     * LESSON_PLAN_CREATED
     */
    LESSON_PLAN_CREATED,
    /**
     * LESSON_PLAN_UPDATED
     */
    LESSON_PLAN_UPDATED,
    /**
     * LESSON_PLAN_DELETED
     */
    LESSON_PLAN_DELETED,
    /**
     * QUESTION_ANSWERED
     */
    QUESTION_ANSWERED,
    /**
     * QUIZ_STARTED
     */
    QUIZ_STARTED,
    /**
     * QUIZ_COMPLETED
     */
    QUIZ_COMPLETED;
}
